version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'paymentsDataBase'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'paymentsUser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'paymentsPassword'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'paymentsPassword'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '4999:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: